CREATE USER c##slownik IDENTIFIED BY ***** DEFAULT TABLESPACE USERS QUOTA 25G on USERS;

GRANT CREATE SESSION TO c##slownik;
GRANT CREATE TABLE TO c##slownik;
GRANT CREATE VIEW TO c##slownik;
GRANT CREATE ANY TRIGGER TO c##slownik;
GRANT CREATE ANY PROCEDURE TO c##slownik;
GRANT CREATE SEQUENCE TO c##slownik;
GRANT CREATE SYNONYM TO c##slownik;

.dicconf